[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "semver"
version = "0.4.11"
update_changelog_on_bump = true
major_version_zero = true
version_files = [
    "cmd/root.go",
]
