---
commitizen:
  major_version_zero: true
  name: cz_conventional_commits
  tag_format: $version
  update_changelog_on_bump: true
  version: 0.3.2
  version_type: semver
  version_files:
    - cmd/version.go:VERSION
