version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: gommitizen
    binary: gommitizen
    main: ./cmd/gommitizen
    ldflags:
      - "-X github.com/freepik-company/gommitizen/internal/version.version={{.Version}}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows

archives:
  - format: binary
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - gommitizen

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: freepik-company
    name: gommitizen
  draft: false
  prerelease: auto

dockers:
  - id: gommitizen
    image_templates:
      - "ghcr.io/freepik-company/gommitizen:{{ .Version }}"
      - "{{ if not .Prerelease }}ghcr.io/freepik-company/gommitizen:latest{{ end }}"
    dockerfile: build/gommitizen/Dockerfile
