name: Go

on:
  push:
    tags: '[0-9].[0-9].[0-9]'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.4'

    - name: Build
      run: go build -v

    - name: Test
      run: |
        git config --global user.email "gommitizen@localhost"
        git config --global user.name "gommitizen"
        go test -v ./...

    - name: Copy, tag with version and create SHA256 checksum
      run: |
        mkdir -p releases
        cp ./gommitizen releases/gommitizen
        sha256sum gommitizen > releases/gommitizen.sha256
    - name: Create a new GitHub release
      uses: softprops/action-gh-release@v0.1.14
      with:
        files: |
          releases/gommitizen
          releases/gommitizen.sha256

