# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    tags: '[0-9].[0-9].[0-9]'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v

    - name: Test
      run: go test -v

    - name: Get the version
      id: version
      run: echo ::set-output name=version::${GITHUB_REF#refs/tags/}

    - name: Copy, tag with version and create SHA256 checksum
      run: |
        mkdir -p releases
        cp ./gommitizen releases/gommitizen_${{ steps.version.outputs.version }}
        sha256sum gommitizen > releases/gommitizen_${{ steps.version.outputs.version }}.sha256
    - name: Create a new GitHub release
      uses: softprops/action-gh-release@v0.1.14
      with:
        files: |
          releases/gommitizen_${{ steps.version.outputs.version }}
          releases/gommitizen_${{ steps.version.outputs.version }}.sha256

