name: Run tests and create a new GitHub release

on:
  workflow_dispatch: {}
  push:
    tags: '[0-9].[0-9].[0-9]'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.4'

      - name: Test
        run: |
          git config --global user.email "gommitizen@localhost"
          git config --global user.name "gommitizen"
          go test -v ./...

      - name: Create a new GitHub release
        uses: softprops/action-gh-release@v0.1.14