name: Run tests and create a new GitHub release

on:
  workflow_dispatch: {}
  push:
    tags: '[0-9].[0-9].[0-9]'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.4'

      - name: Test
        run: |
          git config --global user.email "gommitizen@localhost"
          git config --global user.name "gommitizen"
          go test -v ./...

      - name: Create Release
        id: create_release
        uses: actions/create-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
